### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/IntervalMidpoints#1]
Thank you for the first release

The time zone is set to US

<a href="https://ibb.co/TTb06t1"><img src="https://i.ibb.co/n0n19jB/IMG.jpg" alt="IMG" border="0"></a>

It is 5:39 in egypt , not 8:39 for sunst ,as example

**Comment by islam2hamy** [comment]
<a href="https://ibb.co/Cb0Nj6R"><img src="https://i.ibb.co/jy4BCzn/Screenshot-com-forrestguice-suntimeswidget.jpg" alt="Screenshot-com-forrestguice-suntimeswidget" border="0"></a>

**Comment by forrestguice** [comment]
hrm. It seems that its ignoring the 'system' timezone setting, and is using the 'user defined' value from Suntimes instead (in this case a default value).

I'll fix this asap. A temporary workaround should be to switch the timezone in Suntimes from `System` to `User Defined`.

**Comment by forrestguice** [comment]
This bug should be fixed since `v0.14.1`.
