### ISSUE TITLE
No app icon

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/IntervalMidpoints#5]
Android 7.1.2

**Comment by forrestguice** [comment]
Which icon do you see? 

I see this one on my Android 4.4 device, and my Android 11 device.
![image](https://user-images.githubusercontent.com/10246147/218557309-be6eaca8-72f5-4179-85fd-b716ce190a25.png)

**Comment by islam2hamy** [comment]
![IMG_٢٠٢٣٠٢١٤_٠٣٠٤٢٢](https://user-images.githubusercontent.com/7989030/218612045-2eb48450-35c6-4aa3-b448-375ab01c0917.jpg)

Kiss launcher
