### ISSUE TITLE
BATTERY_OPTIMIZATIONS

### ISSUE THREAD

**Issue by islam2hamy** [forrestguice/IntervalMidpoints#6]
Install new update
Open app 
Click no on
REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

The REQUEST_IGNORE_BATTERY_OPTIMIZATIONS
keep opning again and again

**Comment by forrestguice** [comment]
That is annoying - it will be changed to only ask once.
It should be safe to answer yes though (shouldn't cause actual battery drain), and might actually be required for reliable alarms (that is the motivation for requesting it).

I would downgrade to v0.1.0 for now. The main improvement in v0.1.1 is to fix a bug in Android 11+ where the app flat out crashes, but it doesn't Android 7.
